apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: a
  name: a
spec:
  replicas: 3
  selector:
    matchLabels:
      app: a
  template:
    metadata:
      labels:
        app: a
    spec:
      containers:
      - image: httpd:2.4-alpine3.16
        name: httpd
        resources: {}
status: {}
