apiVersion: v1
kind: Service
metadata:
  labels:
    app: a
  name: a
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: a
  type: NodePort
status:
  loadBalancer: {}