# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#  ______          _                      _____                    ____                               #
# |___  /         (_)                    |  __ \                  / __ \                              #
#    / /    __ _   _    ___    _ __      | |  | |   ___  __   __ | |  | |  _ __    ___                #
#   / /    / _` | | |  / _ \  | '_ \     | |  | |  / _ \ \ \ / / | |  | | | '_ \  / __|               #
#  / /__  | (_| | | | | (_) | | | | |    | |__| | |  __/  \ V /  | |__| | | |_) | \__ \               #
# /_____|  \__,_| |_|  \___/  |_| |_|    |_____/   \___|   \_/    \____/  | .__/  |___/               #
#                                                                         | |                         #
#                                                                         |_|                         #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

replicaCount: 1

image:
  repository: kodekloud
  image: webapp-color
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

securityContext:
  capabilities:
   drop:
     - ALL

service:
  type: NodePort
  port: 80

containerPort: 8080

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

env:
  config: 
    APP_COLOR: "green"
    
  secret: {}
