apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-app.fullname" . }}
  labels:
    {{- include "helm-app.labels" . | nindent 4 }}
data:
{{- range $key, $val := .Values.env.config }}
    {{ $key }}: {{ $val | quote }}
{{- end}}
