apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-app.fullname" . }}
  labels:
    {{- include "helm-app.labels" . | nindent 4 }}
data:
{{- range $key, $val := .Values.env.secret }}
    {{ $key }}: {{ $val | b64enc }}
{{- end}}